### ISSUE TITLE
klogging.common problem

### ISSUE THREAD

**Issue by Zomis** [shafirov/klogging#4]
Using `compile "com.github.lewik.klogging:klogging.common:1.2.10"`
and the code `import klogging.KLoggers`

Gradle complains about `Unresolved reference: KLoggers`

Switching to `com.github.lewik.klogging:klogging.jvm:1.2.10` works fine.

Is there any example project available that uses `klogging.common` ?

**Comment by Lewik** [comment]
`common` or `jvm`?
First `compile` contains `common`
Second `compile` contains `jvm`

What kind of project? `common` or `jvm`?

Usage within `common` project should be same as within `jvm` or `js`

**Comment by Zomis** [comment]
I have three modules in my project: common, js and jvm. I want to include klogging in all of them. At the moment I haven't started coding the js-specific parts though.

So to answer your question: Both common and jvm. I only mentioned that it works when switching to com.github.lewik.klogging:klogging.jvm:1.2.10 - but it is a common module so eventually I *need* to use klogging.common - once I get it working.

**Comment by Lewik** [comment]
`com.github.lewik.klogging:klogging.`**jvm**`:1.2.10` is not a `common`. It's `jvm`.

To get it all work you need add both:
- `compile com.github.lewik.klogging:klogging.`**common**`:1.2.10` in **common**-project
- `compile com.github.lewik.klogging:klogging.`**jvm**`:1.2.10` in **jvm**-project
- `compile com.github.lewik.klogging:klogging.`**js**`:1.2.10` in **js**-project

This lib calls common code (from any kind of code), that should be resolved to platform specific code.

Looks like you`re tring to use jvm part of lib inside common project.

Am I missing something in your question? )

**Comment by Lewik** [comment]
Anyway. I'll add examples in couple of days.

**Comment by Zomis** [comment]
Ignore that I ever mentioned "klogging.jvm", I **am trying** to use klogging.common but for some reason gradle just doesn't allow me to do so. As the first part of my issue says:

Using compile "com.github.lewik.klogging:klogging.common:1.2.10"
and the code import klogging.KLoggers

Gradle complains about Unresolved reference: KLoggers

**Comment by Lewik** [comment]
Just switched my main project to 1.2.10 (klogging and kotlin). No issue.
Actually some time ago there was issue with different package names, but i fixed it. There was switched `.` and `-` or something like this.

Sorry for annoying but I want to be clear:
 - You are using klogging.jvm in your jvm project and klogging.common in your common project.
 - You are trying to compile jvm project.
 - You're not trying to compile common project.
 - You have `expectedBy` in jvm.

And:
 - Did your gradle find jvm and common klogging libs?
 - Could you check 1.2.30?
 - Could you call your common code from jvm project?

I`ll be back in 12-14 hours.

**Comment by Zomis** [comment]
- You are using klogging.jvm in your jvm project and klogging.common in your common project.

Yes, I am.

- You are trying to compile jvm project.

Yes, I am.

- You're not trying to compile common project.

Yes, I am trying to compile the common project as part of my gradle build. Should I not do this?

- You have expectedBy in jvm.

What is `expectedBy`?

I am starting to believe that the issue is with my multiplatform setup in Kotlin...

- Did your gradle find jvm and common klogging libs?

Yes

- Could you check 1.2.30?

Didn't even know that was released as the last commit says "update kotlin to 1.2.10"

- Could you call your common code from jvm project?

Yes, although I might be using the wrong kind of multiplatform setup.

**Comment by Lewik** [comment]
> I am trying to compile the common project as part of my gradle build

common project should be compiled by gradlew/kotlin compiler etc within jvm/js compilation. You should not compile it standalone by yourself. This is impossible: common have no any platform specified.

> What is expectedBy?

I think you can't use common and multiplatform at all without this.
When you use common and jvm projects you should use `expectedBy` to link common and jvm. You need to add `expectedBy` in your deps in gradle in jvm. `expectedBy` "replaces" `compile` when you are trying to link common.
Some examples in https://kotlinlang.org/docs/reference/multiplatform.html

For example my main jvm project use this these rows in `build.gradle`
```
//...
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: kotlin_version
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
    expectedBy project(':entities') //<-- this is the link to common project called "entity"
    //...
    compile "com.github.lewik.klogging:klogging.jvm:$klogging_version"
    //...
}
//...
```

> Didn't even know that was released as the last commit says "update kotlin to 1.2.10"

My fork available under 1.2.30

**Comment by Lewik** [comment]
@Zomis any updates?

**Comment by Zomis** [comment]
Morning! I have realized that it's my multiplatform-setup that is problematic, I have tried fixing it but no complete luck yet - an example using klogging.common would still be helpful.

**Comment by Zomis** [comment]
I have fixed my multiplatform issues and the code is building now!

After changing my code to the correct way of using Kotlin multiplatform I had an issue a while that I had forgotten to add the klogging-js dependency to my javascript module, that also gives "Unresolved reference: KLoggers". Once I realized that the problem was in my Kotlin JS-module, it was easy to solve that,.

Many thanks for all your help @Lewik !
